[workspace]
members = ["server", "client", "shared"]

[workspace.dependencies]
# crossbeam = "0.8"
anyhow = { version = "1.0.72", feaures = ["std"] }
clap = { version = "4.3.21", features = ["derive", "env"] }
tokio = { version = "1.31.0", features = [
    "rt-multi-thread",
    "io-util",
    "macros",
    "net",
    "time",
] }
uuid = { version = "1.4.1", features = ["serde", "v4"] }
serde = { version = "1.0.183", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
